
# This workflow will install Python dependencies and run tests on
# windows and linux systems with a variety of Python versions

# For more information see:
# https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: CI/CD

on:
  push:
  pull_request:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *' # daily

jobs:
  build:
    name: py${{ matrix.python-version }} @ ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: "ubuntu-latest"
            python-version: '3.9'  # first supported
          - os: "windows-latest"
            python-version: '3.9'  # first supported
          - os: "macos-latest"
            python-version: '3.9'  # first supported
          - os: "ubuntu-latest"
            python-version: '3.12'  # latest supported
          - os: "windows-latest"
            python-version: '3.12'  # latest supported
          - os: "macos-latest"
            python-version: '3.12'  # latest supported
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
          fetch-depth: 0
      - uses: conda-incubator/setup-miniconda@v3
        with:
          auto-update-conda: true
          python-version: ${{ matrix.python-version }}
          channel-priority: flexible
          activate-environment: gldas
          auto-activate-base: false
          environment-file: 'environment.yml'
      - name: Print environment infos
        shell: bash -l {0}
        run: |
          conda info -a
          which pip
          which python
          conda list
      - name: Install package and dependencies
        shell: bash -l {0}
        run: |
          pip install -e .[testing,building]
          conda list
      - name: Export Environment
        shell: bash -l {0}
        run: |
          mkdir -p artifacts
          filename=env_py${{ matrix.python-version }}_${{ matrix.os }}.yml
          conda env export --no-builds | grep -v "prefix" > artifacts/$filename
      - name: Run Tests
        shell: bash -l {0}
        run: |
          pytest
      - name: Create wheel and dist package
        shell: bash -l {0}
        run: |
          mkdir -p artifacts/dist
          if [ ${{ matrix.os }} == "linux-latest" ]
          then
            # build dist on linux
            python setup.py sdist --dist-dir artifacts/dist
          fi
          pip install wheel
          python setup.py bdist_wheel --dist-dir artifacts/dist
          ls artifacts/dist
          twine check artifacts/dist/*
      - name: Upload Coverage
        shell: bash -l {0}
        run: |
          pip install coveralls && coveralls --service=github
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          COVERALLS_FLAG_NAME: ${{ matrix.python-version }}
          COVERALLS_PARALLEL: true
      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Artifacts-py${{ matrix.python-version }}-${{ matrix.os }}
          path: artifacts/*

  coveralls:
    name: Submit Coveralls 👚
    needs: build
    runs-on: ubuntu-latest
    container: python:3-slim
    steps:
      - name: Finalize Coveralls Parallel Build
        run: |
          pip3 install --upgrade coveralls
          coveralls --finish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          COVERALLS_SERVICE_NAME: github-actions
  publish:
    name: Upload to PyPI 🚀
    if: startsWith(github.ref, 'refs/tags/v') && startsWith(github.repository, 'TUW-GEO')
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Print environment variables
        run: |
          echo "GITHUB_REF = $GITHUB_REF"
          echo "GITHUB_REPOSITORY = $GITHUB_REPOSITORY"
      - name: Download Artifacts
        uses: actions/download-artifact@v4
        with:
          path: Artifacts
          pattern: Artifacts-*
          merge-multiple: true
      - name: Display downloaded files
        run: ls -aR
      - name: Upload to PyPI
        uses: pypa/gh-action-pypi-publish@v1.12
        with:
          skip-existing: true
          verbose: true
          verify-metadata: true
          packages-dir: Artifacts/dist/
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }} # this needs to be uploaded to github actions secrets
